# Generated by Django 4.2.22 on 2025-06-12 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_transaction_date_transaction_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='inventory_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price_per_gallon',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
