# Generated by Django 4.2.22 on 2025-07-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_stocklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='collected_at_end_of_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='delivery_type',
            field=models.CharField(choices=[('walk_in', 'Walk In'), ('delivery', 'Delivery')], default='walk_in', max_length=20),
        ),
    ]
