# Generated by Django 4.2.22 on 2025-08-01 02:49
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):
    dependencies = [
        ('main', '0007_alter_transaction_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('demo_duration_days', models.IntegerField(default=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Demo Settings',
            },
        ),
    ]