# Generated by Django 4.2.22 on 2025-08-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20250801_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demosettings',
            name='demo_duration_days',
            field=models.IntegerField(default=30),
        ),
    ]
